name: Sonar Cloud Analysis and Quality Gate

on:
  push:
    branches:
      - sonarcloud
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud_and_quality_gate:
    name: SonarCloud and Quality Gate Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run SonarCloud Analysis
        id: sonarcloud_analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Extract Task ID
        id: extract_task_id
        run: |
          report_line=$(echo "${{ steps.sonarcloud_analysis.outputs.full-report }}" | sed -n '281p')
          task_id=$(echo "$report_line" | grep -oP 'https://sonarcloud.io/api/ce/task\?id=[^=]+=\K[^\&]+')
          echo "Task ID: $task_id"
        shell: bash
