name: Sonar Cloud Analysis

on:
  push:
    branches:
      - sonarcloud
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud_analysis:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run SonarCloud Analysis
        id: sonarcloud_analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           job_name: ${{ github.job }}

      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}
 
