name: Sonar Cloud Analysis

on:
  push:
    branches:
      - sonarcloud
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud_analysis:
    name: Run SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run SonarCloud Analysis
        id: sonarcloud_analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Extract Analysis URL
        id: extract_analysis_url
        run: |
          report_logs="${{ steps.sonarcloud_analysis.outputs.logs }}"
          analysis_url=$(echo "$report_logs" | sed -n 's/INFO: More about the report processing at \(https:\/\/sonarcloud\.io\/api\/ce\/task[^ ]*\).*/\1/p')
          echo "Analysis URL: $analysis_url"
          echo "::set-output name=analysis_url::$analysis_url"
